# system
mode: 0
use_parallel: False
num_workers: 1

# dataset
data_path: "/path/to/data"
train_batch_size: 1
image_size: 768
image_filter_size: 256

# model
model_config: "config/v2-vpred-train.yaml"
pretrained_model_path: "/path/to/pretrained_model"
output_path: "/path/to/save/output_data"
ckpt_save_interval: 1
epochs: 20
use_ema: True
clip_grad: False
enable_flash_attention: False

# training
gradient_accumulation_steps: 16

# lr scheduler
scheduler: "iter_exponential"

# optimizer
optim: "adam"